#!/usr/bin/env sh

choice=$(printf "📖 Foxit Reader\n📚 Master PDF Editor\n💻 Code" |
   rofi -dmenu -i -p "Open with" | sed "s/\W//g")

[ ! "$choice" ] && exit

case "$choice" in
   FoxitReader) swallow foxitreader "$1" ;;
   MasterPDFEditor) swallow masterpdfeditor4 "$1" ;;
   Code) swallow code "$1" ;;
esac
