#!/usr/bin/env sh

echo "$1" | grep "\.ar\." && {
   setsid -f "$TERMINAL" \
      --config-file ~/.config/alacritty/alacritty_ar.yml \
      -e "$EDITOR" "$1" > /dev/null 2>&1 &
   exit
}

# case $(file --mime-type "$1" -bL) in
#    text/* | inode/x-empty | application/json | application/octet-stream)
#       "$EDITOR" "$1"
#       ;;
# esac

case $(file --mime-type "$1" -bL) in

   inode/directory)
      $TERMINAL -e lf -last-dir-path ~/.config/lf/lastPath "$1"
      ;;

   text/* | inode/x-empty | application/json | application/octet-stream)
      # ( "$EDITOR" "$1" ) &
      # echo $? > ~/exit
      # "$TERMINAL" -e "$EDITOR" "$1"
      # "$EDITOR" "$1" || "$TERMINAL" -e "$EDITOR" "$1"
      setsid -f "$TERMINAL" -e "$EDITOR" "$1" > /dev/null 2>&1 &
      ;;

   video/*)
      { pgrep mpv || setsid mpv "$1"; } > /dev/null 2>&1 &
      ;;

   application/pdf | application/postscript)
      setsid -f zathura "$1" > /dev/null 2>&1 &
      ;;

   image/gif)
      setsid -f mpv --loop "$1" > /dev/null 2>&1 &
      ;;

   image/*)
      { pgrep feh ||
         setsid -f feh -F -A "setBg %f" -B "black" -d --edit --keep-zoom-vp --start-at "$1"; } > /dev/null 2>&1 &
      ;;

   audio/*)
      { pgrep mpv || setsid -f "$TERMINAL" -e mpv --no-audio-display --loop "$1"; } > /dev/null 2>&1 &
      ;;

   application/x-xz)
      unxz "$1"
      ;;

   application/x-tar)
      tar -xvf "$1"
      ;;

   application/zip)
      unzip "$1" -d "${1%.*}"
      ;;

      # application/x-7z-compressed)
      #     7z x "$1"
      #     ;;

      # *)
      # xdg-open "$1";;

esac
