#!/usr/bin/env sh

# echo "$1" | grep "\.sent$" && {
#    setsid sent "$1" > /dev/null 2>&1 &
#    exit
# }

case $(file --mime-type "$1" -bL) in

   inode/directory)
      $TERMINAL -e lf -last-dir-path ~/.config/lf/lastPath "$1"
      ;;

   text/* | inode/x-empty | application/json | application/octet-stream)
      "$EDITOR" "$1" || { "$TERMINAL" -e "$EDITOR" "$1" & }
      ;;

   video/*)
      { pgrep mpv || setsid mpv "$1"; } > /dev/null 2>&1 &
      ;;

   application/pdf | application/postscript)
      setsid zathura "$1" > /dev/null 2>&1 &
      ;;

   image/gif)
      { pgrep mpv || setsid mpv --loop "$1"; } > /dev/null 2>&1 &
      ;;

   image/*)
      {
         pgrep feh ||
            feh -A "setBg %f" -B "black" -d --edit --keep-zoom-vp --start-at "$1"
      } > /dev/null 2>&1 &
      ;;

   audio/*)
      {
         pgrep mpv ||
            setsid "$TERMINAL" -e mpv --no-audio-display --loop "$1"
      } > /dev/null 2>&1 &
      ;;

   application/x-xz)
      unxz "$1"
      ;;

   application/x-tar)
      tar -xvf "$1"
      ;;

   application/zip)
      unzip "$1" -d "${1%.*}"
      ;;

      # application/x-7z-compressed)
      #     7z x "$1"
      #     ;;

      # *)
      # xdg-open "$1";;

esac
