#!/usr/bin/env sh

data="'{"
for i in "$@"; do
  key=${i%%:*}
  value=${i#*:}
  data="$data\"$key\":\"$value\","
done
data="$data}'"

curl -d "$data" -H 'Content-Type: application/json' http://localhost:5000
# echo "$data"
