#!/usr/bin/env sh

cpu="$(top -b -n 1 | awk '(NR==3){
    if( $8 == "id," )
        print "00"
    else
        printf "%02d", 100 - $8
    }')"

mem="$(free -m | awk '(NR==2){ printf "%04d", $3 }')"
# u=M

temp="$(sensors | awk '(/Core 0/){printf $3}' | sed 's/\.0//; s/+//')"

echo "🌡 $temp   🐎 $cpu%   🧠 $mem"
