#!/bin/sh

source=/sys/class/backlight/"$(ls /sys/class/backlight)"

max="$(cat "$source"/max_brightness)"
current="$(cat "$source"/brightness)"

amount="$((  max * 10 / 100 ))"
increased="$(( current + amount ))"

[ "$increased" -gt "$max" ] && increased="$max"

echo "$increased" > "$source"/brightness
