#!/usr/bin/env sh

# connected ||
#    {
#       notify-send -t 3000 -i $ICONS/disconnected.png "Disconnected"
#       exit 1
#    }

# notify-send -t 3000 -i $ICONS/gitlab.png "Syncing git repos"

for dir in "$GIT"/own/*/; do
    if [ -d "$dir" ]; then
        cd "$dir" || exit 1
        # git pull
        git add .
        [ -z "$(git status --porcelain)" ] && continue
        message=$(timeout 15 rofi -dmenu -i -p "$(pwd | rev | cut -d/ -f1 | rev)")
        [ "$message" ] || message=$(git log -1 | tail -1 | awk '{$1=$1};1')
        git commit -m "$message" && git push &
    fi
done

wait
notify-send -t 3000 -i "$ICONS"/gitlab.png "Done syncing git repos"
