#!/usr/bin/env sh

if ! connected; then
   notify-send -t 3000 -i "$ICONS"/disconnected.png "Disconnected"
   exit 1
fi

notify-send -i "$ICONS/update.png" "Syncing now"

sync-git
sync-calcurse
sync-mail

notify-send -i "$ICONS/update.png" "Done syncing"
