#!/usr/bin/env sh


ICONS=~/.icons/system
android=/mnt/android
disk=/disk/Phone

notify-send -t 3000 -i "$ICONS"/phone.png "Phone Sync" "Time to sync"

timeout 3 sshfs -p "$PORT" "$CARD" $android || {
   notify-send -t 3000 -i "$ICONS"/critical.png "Phone Sync" "Couldn't sync phone!" && exit 1
}

unison -batch -fat $android $disk
fusermount -u $android
notify-send -t 3000 -i "$ICONS"/phone.png "Phone Sync" "Done Syncing"
