#!/usr/bin/env sh

# connected ||
#    {
#       notify-send -t 3000 -i $ICONS/disconnected.png "Disconnected"
#       exit 1
#    }

# notify-send -i "$ICONS/mail.png" "Syncing mail"

mbsync -c ~/.config/isync/mbsyncrc -a
unread=$(find ~/.local/share/mail/gmail/INBOX/new/* -type f 2> /dev/null | wc -l)
[ "$unread" -gt 0 ] && notify-send -t 0 -i "$ICONS/mail.png" \
   "You've got $unread new mail!"

