#!/usr/bin/env sh

# connected ||
#    {
#       notify-send -i $ICONS/disconnected.png "Disconnected"
#       exit 1
#    }

# notify-send -i "$ICONS"/calendar.png "Syncing calcurse"

CALCURSE_CALDAV_PASSWORD=$(gpg -d --batch --passphrase asdlkj ~/.local/share/passwords/salmanabedin@disroot.org.gpg) calcurse-caldav \
   # --init=keep-remote

# notify-send -i "$ICONS"/calendar.png "Done syncing calcurse"
