#!/usr/bin/env sh

notify-send -t 3000 -i "$ICONS"/github.png "Time to rebase git reopos"

for dir in "$GIT"/forks/*/; do
    if [ -d "$dir" ]; then
        cd "$dir" || exit
        git fetch upstream
        git rebase upstream/master
    fi
done
