#!/usr/bin/env sh

dir="Audio Books"

sync() {
    for i in "$@"; do
        cd ~/Drive/"$i" || exit 1
        # drive pull -no-prompt
        drive push -no-prompt ||
            notify-send -t 3000 -i "$ICONS"/critical.png "Couldn't sync with Drive!" ||
            exit 1
    done
}

notify-send -t 3000 -i "$ICONS"/drive.png "Time to Mirror Drive"
sync "$dir"
notify-send -t 3000 -i "$ICONS"/drive.png "Done Mirroring Drive"
