#!/bin/sh
#
# Bluetooth Headset related scripts

connect() {
    bluetoothctl power on
    modprobe iwlwifi bt_coex_active=0

    bluetoothctl connect "E8:EC:A3:27:60:15"

    # bluetoothctl connect "${1:-41:42:B1:BE:00:F3}" ||
    # || bluetoothctl connect "E8:EC:A3:27:60:15" \
    # || bluetoothctl connect "E8:EC:A3:15:05:0D" \
    # || bluetoothctl connect "30:C0:1B:86:61:D5" \
    # || bluetoothctl connect "41:42:B1:BE:00:F3"; then
}

toggle_mic() {
    CARD=$(pactl list short cards | tail -1 | cut -f1)
    if pactl list cards | grep -i "active profile: a2dp" > /dev/null; then
        pactl set-card-profile "$CARD" "headset-head-unit-cvsd"
    else
        pactl set-card-profile "$CARD" "a2dp-sink-aac"
    fi
}

main() {
    case $1 in
        --con | -c) connect ;;
        --tog | -t) toggle_mic ;;
        --mute | -m) amixer set Capture toggle > /dev/null ;;
        *) exit 1 ;;
    esac
}
main "$1"
