#!/bin/sh
#
# Checks if wifi & internet is up or not
# Dependencies: wget

for file in /sys/class/net/w*/operstate; do
   read -r STATE < "$file"
   [ "$STATE" = up ] && wget -q --spider https://google.com || exit 1
done

#===============================================================================
#                             Exp
#===============================================================================

# grep "up" /sys/class/net/w*/operstate > /dev/null && {
#    wget -q --spider http://google.com
# }

# timeout 3 curl google.com > /dev/null 2>&1 || exit 1
# ping -q -c 1 1.1.1.1 > /dev/null 2>&1 \
# || notify-send -t 3000 -i "$ICONS"/disconnected.png "Disconnected"
