#!/bin/sh
#
# Checks if ethernet/wlan & internet is up or not
# Dependencies: wget

read -r ETHERNET < /sys/class/net/eth0/carrier
if [ "$ETHERNET" != 1 ]; then
	set -- /sys/class/net/w*/operstate
	read -r WLAN < "$1"
	[ "$WLAN" = up ] || exit 1
fi
wget -q --spider https://google.com > /dev/null 2>&1 || exit 1

#===============================================================================
#                             Exp
#===============================================================================

# grep "up" /sys/class/net/w*/operstate > /dev/null && {
#    wget -q --spider http://google.com
# }

# timeout 3 curl google.com > /dev/null 2>&1 || exit 1
# ping -q -c 1 1.1.1.1 > /dev/null 2>&1 \
# || notify-send -t 3000 -i "$ICONS"/disconnected.png "Disconnected"
