#!/bin/sh
#
# Extracts Files based on their extensions
# 'extract --clean' cleans up the archive after extraction

[ "$1" = --clean ] && shift && clean=true
ext="${1##*.}"

case $ext in
    tar|gz) mkdir "${1%%.*}" 2> /dev/null && tar xf "$1" -C "${1%%.*}" ;;
    zip) unzip "$1" -d "${1%.*}" ;;
    xz) unxz "$1" ;;
    rar) unrar e "$1" ;;
    7z) 7z x "$1" ;;
    *) exit 1 ;;
    # tar | gz | tgz) tar xf "$1" ;;
        # bz2) tar -xjf "$1" ;;
        # gz) tar xf "$1" -C "${1%.*}" ;;
        # tar) tar -xvf "$1" ;;
        # zip) unzip "$path" -d "${1%.*}" ;;
esac

[ -n "$clean" ] && mv -f "$1" "$TRASH_DIR"
