#!/bin/sh
#
# Cleans up the system (cronjob)
#
# Dependencies: doas, find, notmuch

doas -n -- /usr/bin/sh << eof
pacman -Scc --noconfirm                   # Clears cached packages
pacman -Rns --noconfirm $(pacman -Qttdq)  # Deletes orphaned packages
find ~ -xtype l -delete                   # Deletes dead links
find ~ -type d -empty -delete             # Deletes empty directories
rm -fr /var/cache/pacman/pkg/* ~/.cache   # Clears caches
rm -fr /mnt/internal/trash/. \
  /mnt/internal/trash/*                   # Clears trash
eof

# clears spam
notmuch search --output=files --format=text0 tag:spam | xargs -r0 rm
notmuch new

#===============================================================================
#                             Exp
#===============================================================================

# COMMANDS="\
#    pacman -Scc --noconfirm                   # Clears cached packages
#    pacman -Rns --noconfirm $(pacman -Qttdq)  # Deletes orphaned packages
#    find ~ -xtype l -delete                   # Deletes dead links
#    find ~ -type d -empty -delete             # Deletes empty directories
#    rm -fr /var/cache/pacman/pkg/*            # Clears pacman caches
#    for user in /home/*; do                   # Clear cache
#       rm -fr $user/.cache
#    done
# "

# doas -n $SHELL -c "$COMMANDS" 2> /dev/null

# /var/log/journal/*
# ~/.local/share/Trash/* \
# ~/.local/share/Trash/.*

# canberra-gtk-play -i trash-empty &
