#!/bin/sh
#
# Screen locker
# Dependencies: shuf, i3lock-color, xset, sleep, xdotool

LOCK_STAT=/tmp/LOCK_STAT
BACKGROUND_FORMATTED=/tmp/LOCK_BACKGROUND
FILE_PID_SAVESCREEN=/tmp/LOCK_PID_SAVESCREEN

PATH_WALLPAPERS=~/.local/share/wallpapers
FILE_SCREENSAVER=~/.local/share/screensavers/matrix.mp4

SCREENSAVER_DELAY=5m

kill_screensaver() {
  read -r PID_SAVESCREEN < $FILE_PID_SAVESCREEN
  kill "$PID_SAVESCREEN"
}

savescreen() {
  sleep $SCREENSAVER_DELAY
  mpv -fs --no-osc --no-audio --loop=inf $FILE_SCREENSAVER &
  # ffplay -volume 0 -fs -loop 10 $FILE_SCREENSAVER & \
  echo $! > $FILE_PID_SAVESCREEN
  sleep $SCREENSAVER_DELAY
  xset dpms force off
  kill_screensaver
}

post_unlocked() {
  # setdisplay --bg shuffle
  toggle -n
  : > "$LOCK_STAT"
  kill_screensaver
  pkill -P $$
  # kill $$
}

lock() {
  echo locked > $LOCK_STAT
  toggle -n
  # Fixes the i3lock lock bug
  { xdotool sleep 1 mousemove 0 0 click 1 mousemove restore; } &
  QUOTE=$(shuf -n1 ~/.local/share/misc/quotes)
  i3lock -ekn \
    --indicator --radius 170 --ring-width 3 \
    --ringcolor ffffff --insidecolor 00000000 --linecolor 00000000 \
    --timestr "%H:%M" \
    --time-font sans --timecolor ffffff --timesize 100 \
    --datestr "%a, %d %b" --datepos='tx+0:ty+75' \
    --date-font sans --datecolor ffffff --datesize 30 \
    --greetertext "$QUOTE" --greeterpos 'w/2:100' \
    --greeter-font "Lexend Deca" --greetercolor ffffff --greetersize 25 \
    --pass-volume-keys --pass-media-keys \
    -c 00000000 \
    -i "$BACKGROUND_FORMATTED"
  post_unlocked
}

set_background() {
  convert \
    $(find $PATH_WALLPAPERS -name "*.jpg" -o -name "*.png" | shuf -n1) \
    -resize "$(xrandr | awk '(/current/){print $8 "x" $10 }' | sed 's/,//')"! \
    -fill black -colorize 50% \
    -filter Gaussian \
    -blur 0x3 \
    "$BACKGROUND_FORMATTED"
}

main() {
  [ -s "$LOCK_STAT" ] && exit
  # cat /proc/asound/card*/pcm*/sub*/status | grep RUNNING && exit
  # pacmd list-sink-inputs | grep 'state: RUNNING' && exit
  set_background
  savescreen &
  lock
}
main

# timeout 5m \
#    ffplay -volume 0 -autoexit -exitonkeydown -exitonmousedown -fs -loop 5 \
#    ~/.local/share/screensavers/matrix.mp4 ||
#    xset dpms force off

#===============================================================================
#                             Exp
#===============================================================================

# > /dev/null 2>&1 &
# sleep 5
# kill $!

# if timeout "$dur" \
#    i3lock -ekn \
#    --indicator --radius 170 --ring-width 3 \
#    --ringcolor ffffff --insidecolor 00000000 --linecolor 00000000 \
#    --timestr "%H:%M" \
#    --time-font sans --timecolor ffffff --timesize 100 \
#    --datestr "%a, %d %b" --datepos='tx+0:ty+75' \
#    --date-font sans --datecolor ffffff --datesize 30 \
#    --greetertext "$QUOTE" --greeterpos 'w/2:100' \
#    --greeter-font "Lexend Deca" --greetercolor ffffff --greetersize 25 \
#    --pass-volume-keys --pass-media-keys \
#    -c 00000000 -B 20; then
#    # Unlocked
#    :
# else
#    # Timed out
#    xset dpms force off
# fi

# # Check whether the script was forced or if audio is playing or not
# [ -z "$1" ] && [ "$(pacmd list-sink-inputs)" != "0 sink input(s) available." ] && exit 0

# timeout "$dur"m \
#    ffplay \
#    -volume 0 -exitonkeydown -exitonmousedown -loop "$dur" \
#    -fs ~/.local/share/screensavers/matrix.mp4 \
#    > /dev/null 2>&1 ||
#    systemctl suspend

# xtrlock -f
# timeout 30m xterm -fullscreen -e "sleep 1; cmatrix -s -b -u 10" || systemctl suspend
# timeout 30m xterm -fullscreen -e "sleep 1; rain" || systemctl suspend
# timeout 300 mpv -fs --no-osc --no-audio --loop=inf --no-resume-playback ~/.wallpapers/matrix.mp4 >/dev/null 2>&1 || systectl suspend

# SCREEN=/tmp/screen.png
# ffmpeg -y \
#    -hide_banner \
#    -loglevel error \
#    -f x11grab \
#    -video_size "$(xrandr | awk '(/current/){print $8 "x" $10 }' | sed 's/,//')" \
#    -i "$DISPLAY" \
#    -vframes 1 \
#    $SCREEN
# convert $SCREEN -blur 0x10 $SCREEN
# convert $SCREEN ~/.local/share/images/arch.png -gravity center -composite -matte $SCREEN
# # launch -f $SCREEN
# timeout "$dur"m i3lock -enuc 00000000 -i $SCREEN
