#!/bin/sh
#
# General purpose recording script
# Dependencies: ffmpeg, pinta, xrandr, awk, sed, sleep
# Usage: record [--display | -d] | [--screencast | -s]

RESOLUTION=$(xrandr | awk '(/current/){print $8 "x" $10 }' | sed 's/,//')

case $1 in
    --display | -d)
        # Forked from https://github.com/dylanaraps/bin/blob/master/scr
        FILE=/mnt/internal/downloads/screenshot_"$(date +'%Y-%d_%b-%H_%M_%S')".png
        ffmpeg -y \
            -hide_banner \
            -loglevel error \
            -f x11grab \
            -video_size "$RESOLUTION" \
            -i "$DISPLAY" \
            -vframes 1 \
            "$FILE"
        pinta "$FILE"
        ;;
    --screencast | -s)
        # Forked from https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/dmenurecord
        RECPID=/tmp/recpid


        if [ -f "$RECPID" ]; then
            recpid=$(cat "$RECPID")
            kill -15 "$recpid"
            rm -f "$RECPID"
            sleep 3
            kill -9 "$recpid"
            notify-send "stopped recording"
            exit
        else
            ffmpeg \
                -f pulse \
                -i "$(pactl list sources short | grep -oP '\S*output\S*')" \
                -f x11grab \
                -framerate 30 \
                -s "$RESOLUTION" \
                -i "$DISPLAY" \
                -c:v libx264rgb -preset ultrafast -c:a aac \
                /mnt/internal/downloads/screencast_"$(date +'%Y-%d_%b-%H_%M_%S')".mkv &
            echo $! > "$RECPID"
            notify-send "started recording"
        fi
        #  -crf 0
        #  -f alsa -i default \
        ;;
    -S)
        FILE=/mnt/internal/downloads/screenshot_"$(date +'%Y-%d_%b-%H_%M_%S')".png
        maim -s -u > $FILE
        pinta $FILE
        ;;
    *) exit 1 ;;
esac

# -i :0.0 \
