#!/bin/sh
#
# Launches alacritty as a scratchpad
# Usage:
#        scratchpad [-w WIDTH] [-h HEIGHT] [-x OFFSET_X] [-y OFFSET_y] [-k] CMD...
# Note: Use your window manager to make the class "scratchpad" floating

# ╔══════════════════════════════════════════════════════════════════════
# ║                              Config
# ╚══════════════════════════════════════════════════════════════════════

WIDTH=86
HEIGHT=27
# OFFSET_X=0
# OFFSET_Y=0

# ╔══════════════════════════════════════════════════════════════════════
# ║                              Script
# ╚══════════════════════════════════════════════════════════════════════

CMD="tmux attach"
KILL=

while [ -n "$1" ]; do
  case $1 in
    -w) shift && WIDTH=$1 ;;
    -h) shift && HEIGHT=$1 ;;
    # -x) shift && OFFSET_X=$1 ;;
    # -y) shift && OFFSET_Y=$1 ;;
    -k) KILL=1 ;;
    *) CMD="$CMD $1" ;;
  esac
  shift
done

if [ "$KILL" != 1 ]; then
  CMD="$CMD; read line"
fi

# st -c scratchpad \
# -g "$WIDTH"x"$HEIGHT"+"$OFFSET_X"+"$OFFSET_Y" \
# "$SHELL" -c "$CMD"

alacritty --class scratchpad \
  -o window.dimensions.columns="$WIDTH" \
  -o window.dimensions.lines="$HEIGHT" \
  -e "$SHELL" -c "$CMD"
