#!/bin/sh
#
# Launches your default terminal as a scratchpad
# Usage:
#        scratchpad [-w WIDTH] [-h HEIGHT] [-x OFFSET_X] [-y OFFSET_y] [CMD]
# Note: Use your window manager to make the class "scratchpad" floating

#===============================================================================
#                              Config
#===============================================================================

WIDTH=80
HEIGHT=10
OFFSET_X=0
OFFSET_Y=0

#===============================================================================
#                              Script
#===============================================================================

CMD=

while [ -n "$1" ]; do
  case $1 in
    -w) shift && WIDTH=$1 ;;
    -h) shift && HEIGHT=$1 ;;
    -x) shift && OFFSET_X=$1 ;;
    -y) shift && OFFSET_Y=$1 ;;
    *) CMD="$CMD $1" ;;
  esac
  shift
done

st -c scratchpad \
  -g "$WIDTH"x"$HEIGHT"+"$OFFSET_X"+"$OFFSET_Y" \
  "$SHELL" -c "$CMD; read line"
