#!/bin/sh
#
# Launches your default terminal as a scratchpad
# Note: Use your window manager to make the class "scratchpad" floating

#---------------------------------------
#               Config
#---------------------------------------

WIDTH=80
HEIGHT=10
OFFSET_X=0
OFFSET_Y=0

#---------------------------------------
#               Script
#---------------------------------------

SCRATCHPAD="$TERMINAL -c scratchpad -g "$WIDTH"x$HEIGHT+$OFFSET_X+$OFFSET_Y"

if [ -n "$1" ]; then
   $SCRATCHPAD "$SHELL" -c "$* && read line"
else
   $SCRATCHPAD
fi
