#!/bin/sh
#
# Display related scripts
#
# Dependencies: xrandr, xrdb, grep, find
#
# setdisplay --bg [shuffle,delete] sets & deletes wallpapers
# setdisplay --dpi sets the correct dpi

PATH_WALL=~/.local/share/WALL
PATH_XRESOURCES=~/.config/X11/Xresources
PATH_WALLPAPERS=~/.local/share/wallpapers

set_dpi() {
  INFO=/tmp/display_info

  grep 'Xft.dpi' "$PATH_XRESOURCES" > /dev/null \
    && xrdb -merge "$PATH_XRESOURCES" \
    && return

  xrandr | grep ' connected' > $INFO

  WIDTH_MM=$(awk '{print $NF}' $INFO)
  WIDTH_IN=$(echo "${WIDTH_MM%mm}" | awk '{print $1 * 0.03937007874015748}')

  HEIGHT_MM=$(awk '{print $(NF-2)}' $INFO)
  HEIGHT_IN=$(echo "${HEIGHT_MM%mm}" | awk '{print $1 * 0.03937007874015748}')

  DIAGONAL_IN=$(awk -v w="$WIDTH_IN" -v h="$HEIGHT_IN" \
    'BEGIN{print sqrt(w^2 + h^2)}')

  PX=$(cut -d ' ' -f 4 $INFO)

  WIDTH_PX=${PX%x*}

  TEMP_HEIGHT_PX=${PX#*x}
  HEIGHT_PX=${TEMP_HEIGHT_PX%%+*}

  DIAGONAL_PX=$(awk -v w="$WIDTH_PX" -v h="$HEIGHT_PX" \
    'BEGIN{print sqrt(w^2 +h^2)}')

  DPI=$(awk -v dp="$DIAGONAL_PX" -v di="$DIAGONAL_IN" \
    'BEGIN{print dp / di}')

  echo "Xft.dpi: $DPI" >> "$PATH_XRESOURCES"
  xrdb -merge "$PATH_XRESOURCES"
  rm $INFO
}

_get_wall_path() {
  read -r WALL_PATH < "$PATH_WALL"
  echo $WALL_PATH
}

set_bg() {
  case $1 in
    shuffle | -s)
      find "$PATH_WALLPAPERS" -name "*.jpg" -o -name "*.png" \
        | shuf -n1 > $PATH_WALL
      feh --no-fehbg --bg-scale "$(_get_wall_path)"
      ;;
    delete | -d)
      find "$PATH_WALLPAPERS" -name "$(_get_wall_path)" -delete
      set_bg shuffle
      ;;
    *)
      [ -n "$1" ] && echo "$1" > $PATH_WALL
      feh --no-fehbg --bg-scale "$(_get_wall_path)"
      ;;
  esac
}

while [ -n "$1" ]; do
  case $1 in
    --bg) shift && set_bg "$1" ;;
    --dpi) set_dpi ;;
  esac
  shift
done
