#!/bin/sh
#
# Display related scripts
#
# Dependencies: find
#
# setdisplay --bg [shuffle,delete] sets & deletes wallpapers

PATH_WALL=~/.local/share/WALL
PATH_WALLPAPERS=~/.local/share/wallpapers

_get_wall_path() {
  read -r WALL_PATH < "$PATH_WALL"
  echo $WALL_PATH
}

set_bg() {
  case $1 in
    shuffle | -s)
      find "$PATH_WALLPAPERS" -name "*.jpg" -o -name "*.png" \
        | shuf -n1 > $PATH_WALL
      feh --no-fehbg --bg-scale "$(_get_wall_path)"
      ;;
    delete | -d)
      find "$PATH_WALLPAPERS" -name "$(_get_wall_path)" -delete
      set_bg shuffle
      ;;
    *)
      [ -n "$1" ] && echo "$1" > $PATH_WALL
      feh --no-fehbg --bg-scale "$(_get_wall_path)"
      ;;
  esac
}

while [ -n "$1" ]; do
  case $1 in
    --bg) shift && set_bg "$1" ;;
    --dpi) set_dpi ;;
  esac
  shift
done
