#!/bin/sh
#
# Auto centers tmux panes
#
# Usage:
#        > ~/.config/tmux.conf
#          set-hook -g pane-focus-in "run tmux-center-pane"

[ "$(tmux list-panes | wc -l)" -gt 1 ] && exit

tmux split-window -h -l 16\% "printf '\033[2J\033[H' && read -r line" \; \
  last-pane \; \
  split-window -b -h -l 16\% "printf '\033[2J\033[H' && read -r line" \; \
  last-pane
