#!/bin/sh
#
# Toggles misc operations

DDM=/tmp/ddm

tmux_center() {
   on() {
      tmux split-window -h -l 19\% "clear && read -r line" \; \
         last-pane \; \
         split-window -b -h -l 21\% "clear && read -r line" \; \
         last-pane
   }
   off() {
      tmux kill-pane -t :.+ \; kill-pane -t:.-
   }
   if [ -n "$1" ]; then
      case $1 in
         off) off ;;
         on) on ;;
      esac
      :
   elif [ "$(tmux list-panes | wc -l)" = 1 ]; then
      on
   else
      off
   fi
}

wallreel() {
   REELPID=/tmp/reel_pid

   if [ -s $REELPID ]; then
      kill $(cat $REELPID)
      : > $REELPID
      notify-send -u low -i "$ICONS"/wall.png "Wallpaper Reeling Stopped"
   else
      while :; do
         setdisplay --bg shuffle
         sleep 5m
      done &
      echo $! > $REELPID
      notify-send -u low -i "$ICONS"/wall.png "Wallpaper Reeling Started"
   fi

}

notifications() {
   if [ -s "$DDM" ]; then
      : > "$DDM"
      killall -SIGUSR2 dunst
      sleep 1
      # notify-send -u low -i "$ICONS"/bell.png 'Disturb all you want'
   else
      echo on > "$DDM"
      # notify-send -u low -i "$ICONS"/dnd.png 'Do not disturb'
      sleep 2
      killall -SIGUSR1 dunst
   fi
   # uniblocks -u noti
}

wifi() {
   if pidof iwd > /dev/null; then
      doas systemctl stop iwd
      notify-send -u low -i "$ICONS"/disconnected.png 'Turned Wifi Off'
   else
      doas systemctl start iwd
      notify-send -u low -i "$ICONS"/connected.png 'Turned Wifi On'
   fi
}

focusmode() {
   # if [ -s "$DDM" ]; then
   #    xdo show -a "$STATUSBAR"
   #    bspc config top_padding 35
   # else
   #    xdo hide -a "$STATUSBAR"
   #    bspc config top_padding 0
   # fi
   xdotool key Super+Shift+b
   sleep 0.5 && xdotool key Super+Shift+f
   # tmux set status
   wallreel
   # wifi
   notifications
}

fullscreen() {
   xdotool key Super+Shift+b
   sleep 0.7 && xdotool key Super+Shift+f
}

dont_disturb() {
   wallreel
   notifications
}

screen_key() {
   if pgrep screenkey; then
      pkill screenkey
   else
      screenkey -s small --persist
   fi
}

screen_text() {
   if pgrep screenkey; then
      pkill screenkey
   else
      screenkey -p center -s small --no-whitespace --multiline \
         --ignore Mode_switch --ignore Escape --ignore KP_Left
   fi
}

cam() {
   if pgrep droidcam; then
      pkill droidcam
   else
      droidcam-cli -a 192.168.0.101 4747
   fi
}

dark_mode() {
   VIM=$GIT/own/magpie/.config/nvim/plugin/theme.vim
   ST=$GIT/suckless/st/config.def.h
   DWM=$GIT/suckless/dwm/config.def.h
   QUTE=$GIT/own/magpie/.config/qutebrowser/config.py

   if grep "bg=light" "$VIM" > /dev/null; then
      notify-send "Going dark"
      sed -i 's/=light/=dark/;s/PaperColor/one/' "$VIM"

      sed -i 's/"#eee.*/\/\/&/' "$ST"
      sed -i 's/defaultbg=259/defaultbg=258/' "$ST"
      sed -i 's/defaultfg=258/defaultfg=7/' "$ST"
      sed -i 's/defaultcs=258/defaultcs=7/' "$ST"

      sed -i 's/norm_bg\[\]="#cccccc"/norm_bg\[\]="#000000"/' "$DWM"
      sed -i 's/norm_border\[\]="#000000"/norm_border\[\]="#ffffff"/' "$DWM"
      sed -i 's/norm_fg\[\]="#000000"/norm_fg\[\]="#ffffff"/' "$DWM"

      sed -i 's/# c.colors.web/c.colors.web/' "$QUTE"
   else
      notify-send "Going light"
      sed -i 's/=dark/=light/;s/colorscheme one/colorscheme PaperColor/' "$VIM"

      sed -i 's/\/\/"#eee/"#eee/' "$ST"
      sed -i 's/defaultbg=258/defaultbg=259/' "$ST"
      sed -i 's/defaultfg=7/defaultfg=258/' "$ST"
      sed -i 's/defaultcs=7/defaultcs=258/' "$ST"

      sed -i 's/norm_bg\[\]="#000000"/norm_bg\[\]="#cccccc"/' "$DWM"
      sed -i 's/norm_border\[\]="#ffffff"/norm_border\[\]="#000000"/' "$DWM"
      sed -i 's/norm_fg\[\]="#ffffff"/norm_fg\[\]="#000000"/' "$DWM"

      sed -i 's/c.colors.web.*/# &/' "$QUTE"
   fi

   cd "${ST%/*}" && make && doas -n make install
   cd "${DWM%/*}" && make && doas -n make install

   pkill $TERMINAL 2> /dev/null
   pkill dwm 2> /dev/null
   $TERMINAL -e tmux attach &
}

while :; do
   case $1 in
      --cam | -c) cam ;;
      --dark | -d) dark_mode ;;
      --dnd | -D) dont_disturb ;;
      --fullscreen | -f) fullscreen ;;
      --focus-mode | -F) focusmode ;;
      --noti | -n) notifications ;;
      --wall-reel | -r) wallreel ;;
      --tmux-center | -t) shift && tmux_center "$1" ;;
      --wifi | -w) wifi ;;
      --screen_key) screen_key ;;
      --screen_text) screen_text ;;
      *) break ;;
   esac
   shift
done
