#!/bin/sh
#
# Monitors files/directores for particular changes and runs commands on change events
# Dependencies: inotify-tools
# Usage: watchman [FILE|DIRECTORY] COMMAND

inotifywait -m -e modify "$1" \
    | while read -r line; do
        eval "$2"
    done

#===============================================================================
#                             Exp
#===============================================================================

# inotifywait -m -e move,delete ~/.local/share/mail/INBOX/new \
# | while read -r line; do
# uniblocks -u mail
# done

# echo "
# $GIT/own/magpie
# $GIT/own/private
# " |
#    xargs inotifywait -m -r -e create,moved_to |
#    while read -r line; do
#       cp -frsu -t ~ \
#          "$GIT"/own/magpie/. \
#          "$GIT"/own/private/.
#    done &
