#!/bin/sh
#
# Monitors specific directores for particular changes and runs commands

inotifywait -m -e move,delete ~/.local/share/mail/INBOX/new |
   while read -r line; do
      uniblocks -u mail
   done

#===============================================================================
#                             Exp
#===============================================================================

# echo "
# $GIT/own/magpie
# $GIT/own/private
# " |
#    xargs inotifywait -m -r -e create,moved_to |
#    while read -r line; do
#       cp -frsu -t ~ \
#          "$GIT"/own/magpie/. \
#          "$GIT"/own/private/.
#    done &
