#!/bin/sh

lsblk
echo "partition letter?... "
read -r let
doas umount /dev/sd"$let"1

while getopts "l:w:f" opt; do
   case $opt in
      l) doas -- dd bs=4M if="$OPTARG" of=/dev/sd"$let" status=progress oflag=sync ;;
      w) doas -- woeusb -d "$OPTARG" /dev/sd"$let" --tgt-fs ntfs ;;
      f) printf 'd\n1\nd\2\nn\n\n\n\n\nw' | doas fdisk /dev/sd"$let" && sudo mkfs.vfat /dev/sd"$let"1 ;;
      *) ;;
   esac
done

# [ "$#" -eq 0 ] &&
#   { printf 'd\n1\nd\2\nn\n\n\n\n\nw' | doas fdisk /dev/sd"$let"; } &&
#   sudo mkfs.vfat /dev/sd"$let"1 &&
#   exit

# [ "$1" = -l ] &&
#   doas dd bs=4M if="$2" of=/dev/sd"$let" status=progress oflag=sync &&
#   exit

# [ "$1" = -w ] &&
#   doas woeusb -d $2 /dev/sd$let --tgt-fs ntfs &&
#   exit

# shift $((OPTIND -1))
