#!/bin/sh

choice=$(printf "Log Off\nSuspend\nPower Off\nReboot\nHibernate" |
   $DMENU -p "Bye bye" |
   sed "s/\W//g")

case "$choice" in
   Suspend) systemctl suspend ;;
   LogOff) pkill -KILL -u $USER ;;
   PowerOff) systemctl poweroff ;;
   Reboot) systemctl reboot ;;
   Hibernate) systemctl hibernate ;;
   *) exit ;;
esac
