#!/bin/sh

[ "$(cat /sys/class/power_supply/ADP?/online)" = 1 ] && exit

cap=$(cat /sys/class/power_supply/BAT?/capacity)

if [ "$cap" -lt 10 ]; then
   doas systemctl poweroff
elif [ "$cap" -lt 20 ]; then
   notify-send -t 0 -i "$ICONS"/critical.png 'Low Battery!'
elif [ "$cap" -lt 90 ]; then
   block-charge -f
else
   block-charge -t
fi

# notify-send -t 1000 -i $ICONS/discharging.png "Battery at $cap%"

# [ "$stat" = 1 ] && [ "$cap" -lt 90 ] && { timeout 5 rofi -dmenu -p "30 seconds to shutdown" && notify-send "bypass" || notify-send "shutdown"; }
# [ "$stat" = 0 ] && [ "$cap" -lt 5 ] && ( timeout 30 rofi -dmenu -p "30 seconds to shutdown" && exit || systemctl poweroff )
