#!/bin/sh

ICONS=~/.icons/system

[ "$(cat /sys/class/power_supply/ADP?/online)" = 1 ] && exit

cap=$(cat /sys/class/power_supply/BAT?/capacity)

[ "$cap" -lt 10 ] && systemctl poweroff
[ "$cap" -lt 10 ] && notify-send -t 0 -i $ICONS/critical.png 'Low Battery!'

# notify-send -t 1000 -i $ICONS/discharging.png "Battery at $cap%"

# [ "$stat" = 1 ] && [ "$cap" -lt 90 ] && { timeout 5 rofi -dmenu -p "30 seconds to shutdown" && notify-send "bypass" || notify-send "shutdown"; }
# [ "$stat" = 0 ] && [ "$cap" -lt 5 ] && ( timeout 30 rofi -dmenu -p "30 seconds to shutdown" && exit || systemctl poweroff )
