#!/usr/bin/env sh

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
notify(){ /usr/bin/notify-send -t "$1" -i ~/.icons/system/"$2".png "$3"; }

while getopts "tf" opt; do
	case "$opt" in
		t) notify 1000 charging Charging;;
		f) notify 3000 discharging Discharging;;
        *) ;;
	esac
done

# /usr/bin/sh -c "/home/salman/.local/bin/uniBlocks/refBlock -b"
# /usr/bin/canberra-gtk-play -i device-added

