#!/usr/bin/env sh

# find . -name '*.mp4' -printf '%f\n' | xargs -I% echo file \'%\' >> list
# ffmpeg -f concat -i list -c copy -y all.mp4
# rm list

for vid in "$(pwd)"/*.mkv; do
   printf "%s\n" "file '$vid'" >> list
   ffmpeg -f concat -i list -c copy -y all.mkv
   rm list
done
